### ISSUE TITLE
Compilation fails on Ubuntu 16.04 

### ISSUE THREAD

**Issue by xnfnnlnx** [opcm/pcm#194]
pcm compilation fails on Ubuntu 16.04.5 LTS,  gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609. See error below

Same code compiles on Ubuntu 18.04, with gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0.

Top of the master branch is commit f86174bffc4f7c2f36ce945e1deb51ee46d439eb.

$ make
make -C daemon/daemon/Debug
make[1]: Entering directory '/home-local/xrevolver/src/pcm/daemon/daemon/Debug'
Build PCM
g++ -DPCM_USE_PERF -c ../../../utils.cpp -o utils.o -std=c++11
 
Build PCM
g++ -DPCM_USE_PERF -c ../../../pci.cpp -o pci.o -std=c++11
 
Build PCM
g++ -DPCM_USE_PERF -c ../../../msr.cpp -o msr.o -std=c++11
 
Build PCM
g++ -DPCM_USE_PERF -c ../../../mmio.cpp -o mmio.o -std=c++11
 
Build PCM
g++ -DPCM_USE_PERF -c ../../../client_bw.cpp -o client_bw.o -std=c++11
 
Build PCM
g++ -DPCM_USE_PERF -c ../../../cpucounters.cpp -o cpucounters.o -std=c++11
In file included from ../../../topology.h:42:0,
                 from ../../../cpucounters.cpp:38:
../../../threadpool.h: In member function ‘void ThreadPool::addThread()’:
../../../threadpool.h:120:73: error: no matching function for call to ‘bind(void(ThreadPool*), ThreadPool*)’
         threads_.push_back( std::thread( std::bind( this->execute, this ) ) );
                                                                         ^
In file included from /usr/include/c++/5/memory:79:0,
                 from ../../../msr.h:34,
                 from ../../../cpucounters.h:34,
                 from ../../../cpucounters.cpp:32:
/usr/include/c++/5/functional:1462:5: note: candidate: typename std::_Bind_helper<std::__is_socketlike<_Func>::value, _Func, _BoundArgs ...>::type std::bind(_Func&&, _BoundArgs&& ...) [with _Func = void(ThreadPool*); _BoundArgs = {ThreadPool*}; typename std::_Bind_helper<std::__is_socketlike<_Func>::value, _Func, _BoundArgs ...>::type = std::_Bind<void (*(ThreadPool*))(ThreadPool*)>]
     bind(_Func&& __f, _BoundArgs&&... __args)
     ^
/usr/include/c++/5/functional:1462:5: note:   no known conversion for argument 1 from ‘void(ThreadPool*)’ to ‘void (&&)(ThreadPool*)’
/usr/include/c++/5/functional:1490:5: note: candidate: template<class _Result, class _Func, class ... _BoundArgs> typename std::_Bindres_helper<_Result, _Func, _BoundArgs>::type std::bind(_Func&&, _BoundArgs&& ...)
     bind(_Func&& __f, _BoundArgs&&... __args)
     ^
/usr/include/c++/5/functional:1490:5: note:   template argument deduction/substitution failed:
In file included from ../../../topology.h:42:0,
                 from ../../../cpucounters.cpp:38:
../../../threadpool.h:120:73: note:   couldn't deduce template parameter ‘_Result’
         threads_.push_back( std::thread( std::bind( this->execute, this ) ) );
                                                                         ^
makefile:63: recipe for target 'cpucounters.o' failed
make[1]: [cpucounters.o] Error 1 (ignored)

**Comment by opcm** [comment]
thanks for reporting this issue. Does it compile if you replace "this->execute" with "&ThreadPool::execute" on Ubuntu 16.04?

**Comment by opcm** [comment]
or with "&this->execute"?

**Comment by xnfnnlnx** [comment]
both solutions "&this->execute"   and  "&ThreadPool::execute" work.

**Comment by xnfnnlnx** [comment]
However, later on compilations throws more errors:

g++ -Wall -g -O3 -Wno-unknown-pragmas -std=c++11 -DPCM_USE_PERF -Wextra -c pcm-sensor-server.cpp -o pcm-sensor-server.o
In file included from /usr/include/c++/5/bits/hashtable.h:35:0,
                 from /usr/include/c++/5/unordered_map:47,
                 from pcm-sensor-server.cpp:48:
/usr/include/c++/5/bits/hashtable_policy.h: In instantiation of ‘struct std::__detail::__is_noexcept_hash<HeaderType, std::hash<HeaderType> >’:
/usr/include/c++/5/type_traits:137:12:   required from ‘struct std::__and_<std::__is_fast_hash<std::hash<HeaderType> >, std::__detail::__is_noexcept_hash<HeaderType, std::hash<HeaderType> > >’
/usr/include/c++/5/type_traits:148:38:   required from ‘struct std::__not_<std::__and_<std::__is_fast_hash<std::hash<HeaderType> >, std::__detail::__is_noexcept_hash<HeaderType, std::hash<HeaderType> > > >’
/usr/include/c++/5/bits/unordered_map.h:100:66:   required from ‘class std::unordered_map<HeaderType, std::__cxx11::basic_string<char> >’
pcm-sensor-server.cpp:1304:5:   required from here
/usr/include/c++/5/bits/hashtable_policy.h:85:34: error: no match for call to ‘(const std::hash<HeaderType>) (const HeaderType&)’
  noexcept(declval<const _Hash&>()(declval<const _Key&>()))>
                                  ^
In file included from /usr/include/c++/5/bits/move.h:57:0,
                 from /usr/include/c++/5/bits/stl_pair.h:59,
                 from /usr/include/c++/5/bits/stl_algobase.h:64,
                 from /usr/include/c++/5/bits/char_traits.h:39,
                 from /usr/include/c++/5/ios:40,
                 from /usr/include/c++/5/istream:38,
                 from /usr/include/c++/5/fstream:38,
                 from pcm-sensor-server.cpp:45:
/usr/include/c++/5/type_traits: In instantiation of ‘struct std::__not_<std::__and_<std::__is_fast_hash<std::hash<HeaderType> >, std::__detail::__is_noexcept_hash<HeaderType, std::hash<HeaderType> > > >’:
/usr/include/c++/5/bits/unordered_map.h:100:66:   required from ‘class std::unordered_map<HeaderType, std::__cxx11::basic_string<char> >’
pcm-sensor-server.cpp:1304:5:   required from here
/usr/include/c++/5/type_traits:148:38: error: ‘value’ is not a member of ‘std::__and_<std::__is_fast_hash<std::hash<HeaderType> >, std::__detail::__is_noexcept_hash<HeaderType, std::hash<HeaderType> > >’
     : public integral_constant<bool, !_Pp::value>
                                      ^
In file included from /usr/include/c++/5/unordered_map:48:0,
                 from pcm-sensor-server.cpp:48:
/usr/include/c++/5/bits/unordered_map.h: In instantiation of ‘class std::unordered_map<HeaderType, std::__cxx11::basic_string<char> >’:
pcm-sensor-server.cpp:1304:5:   required from here
/usr/include/c++/5/bits/unordered_map.h:100:66: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<HeaderType> >, std::__detail::__is_noexcept_hash<HeaderType, std::hash<HeaderType> > > >’
       typedef __umap_hashtable<_Key, _Tp, _Hash, _Pred, _Alloc>  _Hashtable;
                                                                  ^
/usr/include/c++/5/bits/unordered_map.h:107:45: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<HeaderType> >, std::__detail::__is_noexcept_hash<HeaderType, std::hash<HeaderType> > > >’
       typedef typename _Hashtable::key_type key_type;
                                             ^
/usr/include/c++/5/bits/unordered_map.h:108:47: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<HeaderType> >, std::__detail::__is_noexcept_hash<HeaderType, std::hash<HeaderType> > > >’
       typedef typename _Hashtable::value_type value_type;
                                               ^
/usr/include/c++/5/bits/unordered_map.h:109:48: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<HeaderType> >, std::__detail::__is_noexcept_hash<HeaderType, std::hash<HeaderType> > > >’
       typedef typename _Hashtable::mapped_type mapped_type;
                                                ^
/usr/include/c++/5/bits/unordered_map.h:110:43: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<HeaderType> >, std::__detail::__is_noexcept_hash<HeaderType, std::hash<HeaderType> > > >’
       typedef typename _Hashtable::hasher hasher;
                                           ^
/usr/include/c++/5/bits/unordered_map.h:111:46: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<HeaderType> >, std::__detail::__is_noexcept_hash<HeaderType, std::hash<HeaderType> > > >’
       typedef typename _Hashtable::key_equal key_equal;
                                              ^
/usr/include/c++/5/bits/unordered_map.h:112:51: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<HeaderType> >, std::__detail::__is_noexcept_hash<HeaderType, std::hash<HeaderType> > > >’
       typedef typename _Hashtable::allocator_type allocator_type;
                                                   ^
/usr/include/c++/5/bits/unordered_map.h:117:45: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<HeaderType> >, std::__detail::__is_noexcept_hash<HeaderType, std::hash<HeaderType> > > >’
       typedef typename _Hashtable::pointer  pointer;
                                             ^
/usr/include/c++/5/bits/unordered_map.h:118:50: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<HeaderType> >, std::__detail::__is_noexcept_hash<HeaderType, std::hash<HeaderType> > > >’
       typedef typename _Hashtable::const_pointer const_pointer;
                                                  ^
/usr/include/c++/5/bits/unordered_map.h:119:47: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<HeaderType> >, std::__detail::__is_noexcept_hash<HeaderType, std::hash<HeaderType> > > >’
       typedef typename _Hashtable::reference  reference;
                                               ^
/usr/include/c++/5/bits/unordered_map.h:120:52: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<HeaderType> >, std::__detail::__is_noexcept_hash<HeaderType, std::hash<HeaderType> > > >’
       typedef typename _Hashtable::const_reference const_reference;
                                                    ^
/usr/include/c++/5/bits/unordered_map.h:121:46: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<HeaderType> >, std::__detail::__is_noexcept_hash<HeaderType, std::hash<HeaderType> > > >’
       typedef typename _Hashtable::iterator  iterator;
                                              ^
/usr/include/c++/5/bits/unordered_map.h:122:51: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<HeaderType> >, std::__detail::__is_noexcept_hash<HeaderType, std::hash<HeaderType> > > >’
       typedef typename _Hashtable::const_iterator const_iterator;
                                                   ^
/usr/include/c++/5/bits/unordered_map.h:123:51: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<HeaderType> >, std::__detail::__is_noexcept_hash<HeaderType, std::hash<HeaderType> > > >’
       typedef typename _Hashtable::local_iterator local_iterator;
                                                   ^
/usr/include/c++/5/bits/unordered_map.h:124:57: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<HeaderType> >, std::__detail::__is_noexcept_hash<HeaderType, std::hash<HeaderType> > > >’
       typedef typename _Hashtable::const_local_iterator const_local_iterator;
                                                         ^
/usr/include/c++/5/bits/unordered_map.h:125:47: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<HeaderType> >, std::__detail::__is_noexcept_hash<HeaderType, std::hash<HeaderType> > > >’
       typedef typename _Hashtable::size_type  size_type;
                                               ^
/usr/include/c++/5/bits/unordered_map.h:126:52: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<HeaderType> >, std::__detail::__is_noexcept_hash<HeaderType, std::hash<HeaderType> > > >’
       typedef typename _Hashtable::difference_type difference_type;
                                                    ^
/usr/include/c++/5/bits/unordered_map.h:280:7: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<HeaderType> >, std::__detail::__is_noexcept_hash<HeaderType, std::hash<HeaderType> > > >’
       operator=(initializer_list<value_type> __l)
       ^
/usr/include/c++/5/bits/unordered_map.h:379:2: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<HeaderType> >, std::__detail::__is_noexcept_hash<HeaderType, std::hash<HeaderType> > > >’
  emplace(_Args&&... __args)
  ^
/usr/include/c++/5/bits/unordered_map.h:432:7: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<HeaderType> >, std::__detail::__is_noexcept_hash<HeaderType, std::hash<HeaderType> > > >’
       insert(const value_type& __x)
       ^
/usr/include/c++/5/bits/unordered_map.h:439:2: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<HeaderType> >, std::__detail::__is_noexcept_hash<HeaderType, std::hash<HeaderType> > > >’
  insert(_Pair&& __x)
  ^
/usr/include/c++/5/bits/unordered_map.h:499:7: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<HeaderType> >, std::__detail::__is_noexcept_hash<HeaderType, std::hash<HeaderType> > > >’
       insert(initializer_list<value_type> __l)
       ^
/usr/include/c++/5/bits/unordered_map.h:645:7: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<HeaderType> >, std::__detail::__is_noexcept_hash<HeaderType, std::hash<HeaderType> > > >’
       equal_range(const key_type& __x)
       ^
/usr/include/c++/5/bits/unordered_map.h:649:7: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<HeaderType> >, std::__detail::__is_noexcept_hash<HeaderType, std::hash<HeaderType> > > >’
       equal_range(const key_type& __x) const
       ^
pcm-sensor-server.cpp:1304:5: error: too many initializers for ‘const std::unordered_map<HeaderType, std::__cxx11::basic_string<char> >’
     };
     ^
pcm-sensor-server.cpp: In static member function ‘static const string& HTTPHeaderProperties::headerTypeAsString(HeaderType)’:
pcm-sensor-server.cpp:1325:42: error: ‘const class std::unordered_map<HeaderType, std::__cxx11::basic_string<char> >’ has no member named ‘at’
         return props.headerTypeToString_.at( ht );
                                          ^
In file included from /usr/include/c++/5/bits/hashtable.h:35:0,
                 from /usr/include/c++/5/unordered_map:47,
                 from pcm-sensor-server.cpp:48:
/usr/include/c++/5/bits/hashtable_policy.h: In instantiation of ‘struct std::__detail::__is_noexcept_hash<MimeType, std::hash<MimeType> >’:
/usr/include/c++/5/type_traits:137:12:   required from ‘struct std::__and_<std::__is_fast_hash<std::hash<MimeType> >, std::__detail::__is_noexcept_hash<MimeType, std::hash<MimeType> > >’
/usr/include/c++/5/type_traits:148:38:   required from ‘struct std::__not_<std::__and_<std::__is_fast_hash<std::hash<MimeType> >, std::__detail::__is_noexcept_hash<MimeType, std::hash<MimeType> > > >’
/usr/include/c++/5/bits/unordered_map.h:100:66:   required from ‘class std::unordered_map<MimeType, std::__cxx11::basic_string<char> >’
pcm-sensor-server.cpp:1700:48:   required from here
/usr/include/c++/5/bits/hashtable_policy.h:85:34: error: no match for call to ‘(const std::hash<MimeType>) (const MimeType&)’
  noexcept(declval<const _Hash&>()(declval<const _Key&>()))>
                                  ^
In file included from /usr/include/c++/5/bits/move.h:57:0,
                 from /usr/include/c++/5/bits/stl_pair.h:59,
                 from /usr/include/c++/5/bits/stl_algobase.h:64,
                 from /usr/include/c++/5/bits/char_traits.h:39,
                 from /usr/include/c++/5/ios:40,
                 from /usr/include/c++/5/istream:38,
                 from /usr/include/c++/5/fstream:38,
                 from pcm-sensor-server.cpp:45:
/usr/include/c++/5/type_traits: In instantiation of ‘struct std::__not_<std::__and_<std::__is_fast_hash<std::hash<MimeType> >, std::__detail::__is_noexcept_hash<MimeType, std::hash<MimeType> > > >’:
/usr/include/c++/5/bits/unordered_map.h:100:66:   required from ‘class std::unordered_map<MimeType, std::__cxx11::basic_string<char> >’
pcm-sensor-server.cpp:1700:48:   required from here
/usr/include/c++/5/type_traits:148:38: error: ‘value’ is not a member of ‘std::__and_<std::__is_fast_hash<std::hash<MimeType> >, std::__detail::__is_noexcept_hash<MimeType, std::hash<MimeType> > >’
     : public integral_constant<bool, !_Pp::value>
                                      ^
In file included from /usr/include/c++/5/unordered_map:48:0,
                 from pcm-sensor-server.cpp:48:
/usr/include/c++/5/bits/unordered_map.h: In instantiation of ‘class std::unordered_map<MimeType, std::__cxx11::basic_string<char> >’:
pcm-sensor-server.cpp:1700:48:   required from here
/usr/include/c++/5/bits/unordered_map.h:100:66: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<MimeType> >, std::__detail::__is_noexcept_hash<MimeType, std::hash<MimeType> > > >’
       typedef __umap_hashtable<_Key, _Tp, _Hash, _Pred, _Alloc>  _Hashtable;
                                                                  ^
/usr/include/c++/5/bits/unordered_map.h:107:45: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<MimeType> >, std::__detail::__is_noexcept_hash<MimeType, std::hash<MimeType> > > >’
       typedef typename _Hashtable::key_type key_type;
                                             ^
/usr/include/c++/5/bits/unordered_map.h:108:47: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<MimeType> >, std::__detail::__is_noexcept_hash<MimeType, std::hash<MimeType> > > >’
       typedef typename _Hashtable::value_type value_type;
                                               ^
/usr/include/c++/5/bits/unordered_map.h:109:48: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<MimeType> >, std::__detail::__is_noexcept_hash<MimeType, std::hash<MimeType> > > >’
       typedef typename _Hashtable::mapped_type mapped_type;
                                                ^
/usr/include/c++/5/bits/unordered_map.h:110:43: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<MimeType> >, std::__detail::__is_noexcept_hash<MimeType, std::hash<MimeType> > > >’
       typedef typename _Hashtable::hasher hasher;
                                           ^
/usr/include/c++/5/bits/unordered_map.h:111:46: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<MimeType> >, std::__detail::__is_noexcept_hash<MimeType, std::hash<MimeType> > > >’
       typedef typename _Hashtable::key_equal key_equal;
                                              ^
/usr/include/c++/5/bits/unordered_map.h:112:51: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<MimeType> >, std::__detail::__is_noexcept_hash<MimeType, std::hash<MimeType> > > >’
       typedef typename _Hashtable::allocator_type allocator_type;
                                                   ^
/usr/include/c++/5/bits/unordered_map.h:117:45: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<MimeType> >, std::__detail::__is_noexcept_hash<MimeType, std::hash<MimeType> > > >’
       typedef typename _Hashtable::pointer  pointer;
                                             ^
/usr/include/c++/5/bits/unordered_map.h:118:50: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<MimeType> >, std::__detail::__is_noexcept_hash<MimeType, std::hash<MimeType> > > >’
       typedef typename _Hashtable::const_pointer const_pointer;
                                                  ^
/usr/include/c++/5/bits/unordered_map.h:119:47: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<MimeType> >, std::__detail::__is_noexcept_hash<MimeType, std::hash<MimeType> > > >’
       typedef typename _Hashtable::reference  reference;
                                               ^
/usr/include/c++/5/bits/unordered_map.h:120:52: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<MimeType> >, std::__detail::__is_noexcept_hash<MimeType, std::hash<MimeType> > > >’
       typedef typename _Hashtable::const_reference const_reference;
                                                    ^
/usr/include/c++/5/bits/unordered_map.h:121:46: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<MimeType> >, std::__detail::__is_noexcept_hash<MimeType, std::hash<MimeType> > > >’
       typedef typename _Hashtable::iterator  iterator;
                                              ^
/usr/include/c++/5/bits/unordered_map.h:122:51: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<MimeType> >, std::__detail::__is_noexcept_hash<MimeType, std::hash<MimeType> > > >’
       typedef typename _Hashtable::const_iterator const_iterator;
                                                   ^
/usr/include/c++/5/bits/unordered_map.h:123:51: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<MimeType> >, std::__detail::__is_noexcept_hash<MimeType, std::hash<MimeType> > > >’
       typedef typename _Hashtable::local_iterator local_iterator;
                                                   ^
/usr/include/c++/5/bits/unordered_map.h:124:57: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<MimeType> >, std::__detail::__is_noexcept_hash<MimeType, std::hash<MimeType> > > >’
       typedef typename _Hashtable::const_local_iterator const_local_iterator;
                                                         ^
/usr/include/c++/5/bits/unordered_map.h:125:47: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<MimeType> >, std::__detail::__is_noexcept_hash<MimeType, std::hash<MimeType> > > >’
       typedef typename _Hashtable::size_type  size_type;
                                               ^
/usr/include/c++/5/bits/unordered_map.h:126:52: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<MimeType> >, std::__detail::__is_noexcept_hash<MimeType, std::hash<MimeType> > > >’
       typedef typename _Hashtable::difference_type difference_type;
                                                    ^
/usr/include/c++/5/bits/unordered_map.h:280:7: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<MimeType> >, std::__detail::__is_noexcept_hash<MimeType, std::hash<MimeType> > > >’
       operator=(initializer_list<value_type> __l)
       ^
/usr/include/c++/5/bits/unordered_map.h:379:2: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<MimeType> >, std::__detail::__is_noexcept_hash<MimeType, std::hash<MimeType> > > >’
  emplace(_Args&&... __args)
  ^
/usr/include/c++/5/bits/unordered_map.h:432:7: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<MimeType> >, std::__detail::__is_noexcept_hash<MimeType, std::hash<MimeType> > > >’
       insert(const value_type& __x)
       ^
/usr/include/c++/5/bits/unordered_map.h:439:2: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<MimeType> >, std::__detail::__is_noexcept_hash<MimeType, std::hash<MimeType> > > >’
  insert(_Pair&& __x)
  ^
/usr/include/c++/5/bits/unordered_map.h:499:7: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<MimeType> >, std::__detail::__is_noexcept_hash<MimeType, std::hash<MimeType> > > >’
       insert(initializer_list<value_type> __l)
       ^
/usr/include/c++/5/bits/unordered_map.h:645:7: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<MimeType> >, std::__detail::__is_noexcept_hash<MimeType, std::hash<MimeType> > > >’
       equal_range(const key_type& __x)
       ^
/usr/include/c++/5/bits/unordered_map.h:649:7: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<MimeType> >, std::__detail::__is_noexcept_hash<MimeType, std::hash<MimeType> > > >’
       equal_range(const key_type& __x) const
       ^
pcm-sensor-server.cpp: At global scope:
pcm-sensor-server.cpp:1706:1: error: too many initializers for ‘std::unordered_map<MimeType, std::__cxx11::basic_string<char> >’
 };
 ^
pcm-sensor-server.cpp: In member function ‘MimeType HTTPHeader::headerValueAsMimeType() const’:
pcm-sensor-server.cpp:1820:29: error: no matching function for call to ‘begin(std::unordered_map<MimeType, std::__cxx11::basic_string<char> >&)’
             for( auto& mt : mimeTypeMap ) {
                             ^
In file included from /usr/include/c++/5/string:51:0,
                 from /usr/include/c++/5/bits/locale_classes.h:40,
                 from /usr/include/c++/5/bits/ios_base.h:41,
                 from /usr/include/c++/5/ios:42,
                 from /usr/include/c++/5/istream:38,
                 from /usr/include/c++/5/fstream:38,
                 from pcm-sensor-server.cpp:45:
/usr/include/c++/5/bits/range_access.h:87:5: note: candidate: template<class _Tp, long unsigned int _Nm> _Tp* std::begin(_Tp (&)[_Nm])
     begin(_Tp (&__arr)[_Nm])
     ^
/usr/include/c++/5/bits/range_access.h:87:5: note:   template argument deduction/substitution failed:
pcm-sensor-server.cpp:1820:29: note:   mismatched types ‘_Tp [_Nm]’ and ‘std::unordered_map<MimeType, std::__cxx11::basic_string<char> >’
             for( auto& mt : mimeTypeMap ) {
                             ^
In file included from /usr/include/c++/5/string:51:0,
                 from /usr/include/c++/5/bits/locale_classes.h:40,
                 from /usr/include/c++/5/bits/ios_base.h:41,
                 from /usr/include/c++/5/ios:42,
                 from /usr/include/c++/5/istream:38,
                 from /usr/include/c++/5/fstream:38,
                 from pcm-sensor-server.cpp:45:
/usr/include/c++/5/bits/range_access.h:58:5: note: candidate: template<class _Container> decltype (__cont.begin()) std::begin(const _Container&)
     begin(const _Container& __cont) -> decltype(__cont.begin())
     ^
/usr/include/c++/5/bits/range_access.h:58:5: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/range_access.h: In substitution of ‘template<class _Container> decltype (__cont.begin()) std::begin(const _Container&) [with _Container = std::unordered_map<MimeType, std::__cxx11::basic_string<char> >]’:
pcm-sensor-server.cpp:1820:29:   required from here
/usr/include/c++/5/bits/range_access.h:58:5: error: ‘const class std::unordered_map<MimeType, std::__cxx11::basic_string<char> >’ has no member named ‘begin’
/usr/include/c++/5/bits/range_access.h:48:5: note: candidate: template<class _Container> decltype (__cont.begin()) std::begin(_Container&)
     begin(_Container& __cont) -> decltype(__cont.begin())
     ^
/usr/include/c++/5/bits/range_access.h:48:5: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/range_access.h: In substitution of ‘template<class _Container> decltype (__cont.begin()) std::begin(_Container&) [with _Container = std::unordered_map<MimeType, std::__cxx11::basic_string<char> >]’:
pcm-sensor-server.cpp:1820:29:   required from here
/usr/include/c++/5/bits/range_access.h:48:5: error: ‘class std::unordered_map<MimeType, std::__cxx11::basic_string<char> >’ has no member named ‘begin’

**Comment by ogbrugge** [comment]
Then gcc 5.4.0 has still has the problem with hash that we first encountered in gcc 4.8.X. It is therefore also not fully compatible with c++11. Is there a newer compiler on 16.04 LTS? like gcc 6? That one appears to be more c++-11 compatible than 4.8.5 and in my experience compiles hash fine, a least on SLES with the gcc6-c++ compiler from the SUSE SDK.

**Comment by xnfnnlnx** [comment]
I think gcc 5.4.0 is the most recent for the Ubuntu 16.04 release

**Comment by xnfnnlnx** [comment]
Probably, as a workaround, it is possible to install more recent gcc from ubuntu-toolchain-r/test PPA
[ubuntu-toolchain-r/test](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test)

Not sure how it will affect a development environment on Ubuntu 16.04

**Comment by opcm** [comment]
error: no match for call to ‘(const std::hash<HeaderType>) (const HeaderType&)’
Seems to hit a defect in the c++11 standard?
One can try workarounds: https://stackoverflow.com/questions/18837857/cant-use-enum-class-as-unordered-map-key

**Comment by ogbrugge** [comment]
Normally the compilers in distros are pretty well contained so i do not expect many problems with installing a second or third compiler, at least this is my experience on SLES and RHEL. The C++ 11 standard is 9 years old by now, one can expect a compliant compiler by now :-)

**Comment by opcm** [comment]
Would this fix it?
std::unordered_map<enum HeaderType, std::string> 
=>
std::unordered_map<enum HeaderType, std::string, std::hash<int> >

**Comment by opcm** [comment]
Defect in the standard, not compiler.

Copying from stackoverflow:

This was considered a defect in the standard, and was fixed in C++14: http://www.open-std.org/jtc1/sc22/wg21/docs/lwg-defects.html#2148

This is fixed in the version of libstdc++ shipping with gcc as of 6.1: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60970.

It was fixed in clang's libc++ in 2013: http://lists.cs.uiuc.edu/pipermail/cfe-commits/Week-of-Mon-20130902/087778.html

**Comment by xnfnnlnx** [comment]
Yes, now it works. Attached is the diff with all changes you proposed to apply. 
[pcm-patch.txt](https://github.com/opcm/pcm/files/4604660/pcm-patch.txt)

**Comment by ogbrugge** [comment]
I don't understand the reason for the & in the threadpool, this->execute is a pointer already...

Oh well, can you submit this as a patch? This way you get proper credit for doing the work.

**Comment by ogbrugge** [comment]
One comment, can you the remove the unnecessary white space?

hash<int> >     ==>       hash<int>>

**Comment by xnfnnlnx** [comment]
Sure, please see attached the fixed patch.

Credit should go to @opcm, I just tested proposed fix.

[pcm-patch2.txt](https://github.com/opcm/pcm/files/4604989/pcm-patch2.txt)

**Comment by opcm** [comment]
@xnfnnlnx  , could you please do me a favor and submit this patch as a pull request? After all most of the work here was your testing.

**Comment by xnfnnlnx** [comment]
@opcm, NP, will do that tomorrow

**Comment by ogbrugge** [comment]
> @xnfnnlnx , could you please do me a favor and submit this patch as a pull request? After all most of the work here was your testing.

This is what i meant as well, sorry for the confusion.

**Comment by xnfnnlnx** [comment]
I submitted pull request #195

**Comment by opcm** [comment]
resolved in master
