### ISSUE TITLE
copy elision warning

### ISSUE THREAD

**Issue by baketchum** [opcm/pcm#238]
clang is complaining about return statements that include std::move:

        return std::move( ccs );

  For example. And generally speaking they are a bad idea as explained here:

http://www.cplusplus.com/forum/general/186411/

  Do we care to fix these?

**Comment by ogbrugge** [comment]
I think I wanted to force move semantics here but if return already implies that as the discussion you linked indicates then it should work without but I am not sure about GC 4.8.5 supporting that. It is the oldest compiler we need to support for a while unless we force a newer C++ standard... you are More than welcome to try though and send a pull request. I am not back in the office or have access  to a computer until early November...

**Comment by baketchum** [comment]
At present, the compile fails for gcc 4.8.5:

dashboard.cpp: In function 'std::string pcm::getPCMDashboardJSON(pcm::PCMDashboardType, int, int, int)':
dashboard.cpp:694:28: error: 'to_string' is not a member of 'std'
             const auto S = std::to_string(s);
                            ^
dashboard.cpp:707:24: error: 'to_string' is not a member of 'std'
         const auto S = std::to_string(s);
                        ^
dashboard.cpp: In lambda function:
dashboard.cpp:630:9: warning: control reaches end of non-void function [-Wreturn-type]
         };
         ^
gmake: *** [Makefile:89: dashboard.o] Error 1

**Comment by opcm** [comment]
hm.. this builds fine with g++ 4.8.4 : https://travis-ci.com/github/opcm/pcm/jobs/397286836

may be an additional header needs to be included for 4.8.5?

**Comment by baketchum** [comment]
The compile failure appears to be a FreeBSD gcc 4.8.5 issue with the -std=c++11 support. 

I addressed the clang compiler warnings and created a PR in the event the changes are of interest.

**Comment by opcm** [comment]
@baketchum could you please attach the warning log from clang that you have? Are the warnings the same as in https://travis-ci.com/github/opcm/pcm/jobs/397418155
?

**Comment by baketchum** [comment]
Attached to the PR.
